sudo: required
matrix:
  include:
  - env: GHCVER=7.10
  - env: GHCVER=8.0
  - env: GHCVER=8.2
  - env: GHCVER=8.4
  - env: GHCVER=8.6
  - env: GHCVER=head
  - os: osx

script:
- git clone https://github.com/jacereda/fsatrace.git .fsatrace
# Works - (cd .fsatrace && git checkout 678e29da6f1947dba762b291de5cd794a9bba51e)
# Works - (cd .fsatrace && git checkout f8b3e7642f5a9376bdc97c6e2d9b52d77e6d9bcd)
# Fails - (cd .fsatrace && git checkout 4f9f599f6f200ff88d92a752f68817d166bc4b8c)
- (cd .fsatrace && git checkout e8d46cf3755117dc4e9affa1b9ebd3f108af8921)
- (cd .fsatrace && make)
- export PATH=$PATH:`pwd`/.fsatrace
- fsatrace v - -- echo fsatrace works
- curl -sSL https://raw.github.com/ndmitchell/neil/master/travis.sh | sh

deploy:
  provider: releases
  api_key:
    secure: "aFuskonICPg8VRvkui/uvJ1+/Cf5eMM78gQGOon1x2tzu16KBpmXfY+O4yCGSFy1NIuoRZ1OU1LpwIgCcb71AxHz4CTZk+Xjf5dwqy7b7iOzbxYHZJUzUC1OpwsWNEqd7MwAjdcDNg4w5kqLZtDMtf9DuUXPzYTj+iM6HLwZQVg="
  file_glob: true
  file:  travis-release/*
  skip_cleanup: true
  on:
    tags: true
